# 텐서플로우

In [2]:
# 모듈 사용하기
import tensorflow as tf

In [3]:
# tf 정보 확인
print('info ==>', tf.version)
# tf 버전 확인
print('version ==>', tf.__version__)

info ==> <module 'tensorflow._api.v2.version' from '/opt/anaconda3/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>
version ==> 2.4.1


# tensorflow 2.0에서 1.0코드 실행 방법(Session 사용)

In [ ]:
import tensorflow.compat.v1 as tf
tf.enable_eager_execution()
tf.disable_v2_behavior()
tf.__version__

In [ ]:
# 변수초기화
sess = tf.Session()
sess.run(global_variables_initializer())

# 상수, 변수 생성
* contant: 변하지 않고 고정된 값
* Variable: 투입값에 따라 변하는 숫자

두 개가 그렇게 큰 차이가 없다

In [4]:
# 상수 생성
a = tf.constant(1.0, name='a')
# 변수 생성
b = tf.Variable(1.5)

* get_variable: 변수의 이름과 범위를 지정해주면 랜덤으로 생성해준다. (version 1.0)

In [17]:
c = tf.Variable(tf.zeros(shape=(2,3)), name="zero")
d = tf.Variable(tf.ones(shape=(2)), name="one")

# 출력하기

In [5]:
# 출력하기 (version 1.x)
# sess = tf.Session()
# sees.run(a)

In [19]:
# 출력하기 (version 2.x)
tf.print(a)
tf.print(b)
tf.print(c)
tf.print(d)

1
1.5
[[0 0 0]
 [0 0 0]]
[1 1]


# TF 연산자

* 사칙연산 (add, subtract, multiply, divide)

In [39]:
a = tf.constant(4)
b = tf.constant(2)
tf.print(a, b)

4 2


In [41]:
# 덧셈
tf.add(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [43]:
# 뺄셈
tf.subtract(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [44]:
# 곱셈
tf.multiply(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [45]:
# 나눗셈
tf.divide(a, b)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [46]:
# a의 b제곱 
tf.pow(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=16>